### ISSUE TITLE
LoadID Async Request Bug

### ISSUE THREAD

**Issue by markhayden** [lytics/jstag#46]
When using the `loadid` param to merge profiles across domains there is a bug when more than one event has been queued to send. 

Here is what is happening:

1. Multiple `jstag.send` events are being fired on the first page view. Bear in mind that this is a first time visitor, no cookies, never visited, etc. 
2. When the queue is flushed, as part of the `jstag.send` function we resolve the UID. It should check for a `seerid` cookie and then if that fails, because of the `loadid` flag it will request a cookie from the lytics.io domain.
3. These requests are being handled asynchronously, meaning all three are being processed before a response is received on the initial uid request from lytics.io. As such, three events are forwarded to the collection endpoint all with unique UIDs. This is causing inflated numbers and orphaned fragments for for every new visitor.

Here are a couple of approaches we could take to fix it:

1. We already have the ability to block all send requests. In the event of `loadid=true` we could block all requests and resolve the UID. As soon as the UID has been properly resolved / seerid saved we could then remove the send block and process events normally. This should prevent subsequent requests for the third party UID from the `lytics.io` domain.
2. We could also make each `jstag.send` request aware of any loadid UID resolution requests that are pending. In the case of pending requests we'd add the send request to a callback of some sort to be flushed when the UID gets resolved properly. 

Both seem like fine approaches though I feel like number 1 would make fore more bulletproof code in that making that third party request is directly related to a one time config value and can not be handled per send so doing the resolution within each send seems repetitive. 

legacy function: https://github.com/lytics/jstag/blob/develop/src/legacy/io.js#L158

**Comment by ddrazba-lytics** [comment]
@markhayden / @humanchimp I see some progress ... what are the next steps on this one for Source Media, we were going to have them upgrade to v3 of jstag correct?

**Comment by markhayden** [comment]
let me get back to you on this one on monday. we had some deploy issues with jstag3 that need to be resolved before we can get them moved over but yes that will be the next step for all of their sites.

**Comment by humanchimp** [comment]
I'll look into the deployment issues today, but we can also bypass the deployment if necessary since Source Media is just including the jstag directly using a `<script>` element

**Comment by ddrazba-lytics** [comment]
Hey @markhayden / @humanchimp whats the eta on having this ready for Source Media?  Thanks.

**Comment by humanchimp** [comment]
It would be best for me if we could bypass the deployment issues for now, since Source Media is using a `<script>` element  to load the tag, as mentioned [here](https://github.com/lytics/jstag/issues/46#issuecomment-307826629). AFAIK, there is nothing preventing that from happening today

**Comment by ddrazba-lytics** [comment]
Okay, i think the plan was that we were goign to give them a new tag so that the cookie changes would take affect.  Is that still necessary?
